services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: analytics
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env.local  # ← AQUÍ: Lee variables de .env.local
    environment:
      # Override específicas para Docker (solo las que cambian)
      ENVIRONMENT: "docker"
      DB_HOST: "db"  # ← Cambia de localhost a db para Docker
      # Todas las demás vienen de .env.local
    volumes:
      - .:/app
      - media:/app/media
    ports:
      - "8000:8000"

volumes:
  dbdata:
  media: